### ISSUE TITLE
About rotation and a request.

### ISSUE THREAD

**Issue by ghost** [Tjstretchalot/SharpMath2#1]
Hey there,

This library is bloody amazing. Easily implemented it (I already had a polygon/shape class ready so it really was a surprise I didn't have to change much!)

I have a two requests - one of them is that if you could make it possible I could just reset the Rotation2 cos/sin instead of making a new object every time (and the same would go for a Polygon2.)

Also I'm wondering how I'd change the rotation based on the example collision between polygons (I probably missed something really obvious.)

`
        Tuple<Vector2, float> mtv;
        /// <summary>
        /// Upon collision with another quad object
        /// </summary>
        /// <param name="object">The object we've colldied with.</param>
        public virtual void OnCollision(QuadObject @object)
        {
            mtv = Polygon2.IntersectMTV(
                Shape.CollisionBox, @object.Shape.CollisionBox, Position, @object.Position, Shape.CollisionBoxRotation, @object.Shape.CollisionBoxRotation);

            if (mtv != null)
            {
                Position += mtv.Item1 * mtv.Item2;
                // Rotation += ?
            }

        }`

As for re-using the existing polygon, I mean something along the lines of:
`
        /// <summary>
        /// The shape of the object.
        /// </summary>
        private Vector2[] Points {
            get {
                return _Points;
            }
            set
            {
                OrderClockwise(ref _Points);
                CollisionBox = new Polygon2(_Points);    
                // CollisionBox.SetPoints(_Points);
            }
        }
`

**Comment by Tjstretchalot** [comment]
Hello Eddie!

Thank you for the issue! This library is also compatible with my ThetaSharp library so consider checking it out too if you need pathfinding! https://github.com/Tjstretchalot/ThetaStarSharp

As for changing rotation between polygons after collision, this is a pretty complicated question that I haven't gotten yet into the project that this library is for, and so far I've been avoiding answering.

In order to accurately determine the required rotation, you need is determine the location of impact, which you can't find with SAT. Additionally, you need to know how both polygons were moving prior to intersection. If you're allowed to move and rotate a polygon to prevent intersection, you actually have many different ways of resolving the collision so there isn't a good one-function approach that I have found yet. Let me know how you end up solving this problem, though!

Currently I have set up rotation calculations to be guessed differently based on the type of interaction I want. For example, send the polygon spinning when it hits a wall with random angular velocity. Typically this looks good enough 

-----


As for not having to generate new polygons, the reason I didn't add that is it's not an accurate reflection of the performance cost of changing vertices. In my projects, I try to save certain "standard" collision polygons. If I have something that rotates, I only have collision accuracy to about 20 degrees, and between those angles it's purely visual. The reason for this is most calculations on polygons are very cacheable - finding the normals and longest cross-sectional area, etc. So re-using a polygon removes a lot of overhead. Is that possible with your project?

When I first started this project I thought that I could reduce the calculation with rotating polygons because it does share some important features, but I later found this not to work very well and it ended up being ~3x slower than just making a new rotated polygon. There is some refactoring to do and documentation to update on that end\

---

Also realize that there is a very minimal performance cost with generating new "Rotation2"s - it's the equivalent as saving 3 integers, since everything is final, and it's pass by value. The sole purpose of this class is to reduce method signatures and complexity, while avoiding the much more comparatively expensive cosine and sine functions. There is a constructor that accepts the cosine and sine if you are already calculating those.

**Comment by ghost** [comment]
Hey Tjstretch,

Seems like you really know your stuff. Yeah the reason I ask for just being able to change them is because I feel uncomfortable just creating new stuff all the time, and I've increased my performance a ton by changing rectangle position width and heights, instead of making a new one - so I pretty much had the idea that doing this as much as possible would always be great.

As for the rotation, well they don't need to be physic styled for me - I think what I'll do is add angular velocity based on the angle between polygon A and polygon B - then multiple it by some random factor depending on both velocities of the polygon.

`AngularAcceleration += (A.AngleTo(b)) * (A.Velocity.Length() + B.Velocity.Length())`

**Comment by Tjstretchalot** [comment]
Eddie,

You are correct it's not a good idea to create new things all the time. However, creating new Polygons (or rotating them) is a very expensive operation, so that is why I have the constructor be required for it (to help show how expensive the operation is).

The best way to increase performance is to utilize anything you know about your specific usecase. I notice you have quads, do any of them share the same size? They should reuse polygons. Are these quads moving freely, or do they move on a ground. If they are on the ground, do they spend the vast majority of their time at any particular set of rotations (for example, either flat, up a 30 degree ramp, up a 60 degree ramp, or vertical)?

Another thing you can do if you want any-angle polygons but you are in mostly empty space (no gravity to push you around, no ledges, only "rare" collisions) is only generate the polygons at the moment of collision.

Lastly, if none of those things work, there's certainly room to improve this library. Many functions accept a Rotation on a polygon, but some might throw an exception if the rotation is not 0. Look into those functions for your particular case (ie https://github.com/Tjstretchalot/SharpMath2/blob/master/Math2/Polygon2.cs#L230) and see if you can spot any performance improvements there (or if they throw any NotImplementedExceptions). Looking into what the cost is for the rotation might give insight into the performance. If it is working for you, or you can implement that function, you won't have to generate new polygons. For intersection MTV, the cost to pass in rotation is fairly minor. For minimum distance, it's not implemented. So that's the range you are dealing with :)

Similarly, if you know you are dealing with quads there's definitely a lot of believable angular rotations you can give them, and you can use the game rules to avoid running into where such approximations would look funny.

**Comment by ghost** [comment]
"They should reuse polygons. "Indeed, which is when I start working with animations I need to build the polygons of the animations before hand - in a sort of "model", I could then just select the image index of the texture and model polygon - this is why I love this library a lot - I had a lot of issues trying to achieve this without a lot of hassle in Farseer (which mind you, I do not hate, it's great.)

**Comment by Tjstretchalot** [comment]
How did you end up solving this? I have a lot on my plate but I'm not opposed to getting to any changes if you have any specific suggestions in mind. I will play devils advocate just because I want to make the sure the work is worth it, but I'm very convincible if you can give a specific use-case and do some performance comparisons 👍
